us_chicago:
  country: "us"
  city: "chicago"

  input_csv: "../../data/datasets/municipal_reports/us/municipal_us_chicago_311.csv"
  output_csv: "../../data/datasets/weather/us/weather_us_chicago_open-meteo.csv"

  keep_cols:
    sr_number: report_id
    latitude: latitude
    longitude: longitude
    created_date: reported_datetime
  id_col: "sr_number"
  lat_col: "latitude"
  lon_col: "longitude"
  date_col: "created_date"

  hours_before: 23
  hours_after: 0
  
  max_workers: 5
  max_retries: 10
  backoff: 2 

  weather_api:
    query:
      hourly:
        - temperature_2m
        - relative_humidity_2m
        - precipitation
        - windspeed_10m
      daily: null
      timezone: "UTC"

  air_api:
    query:
      hourly:
        - pm10
        - pm2_5
        - carbon_monoxide
        - nitrogen_dioxide
        - ozone
        - sulphur_dioxide
      timezone: "UTC"


us_newyork:
  country: "us"
  city: "newyork"

  input_csv: "../../data/datasets/municipal_reports/us/municipal_us_newyork_311.csv"
  output_csv: "../../data/datasets/weather/us/weather_us_newyork_open-meteo.csv"

  keep_cols:
    unique_key: report_id
    latitude: latitude
    longitude: longitude
    created_date: reported_datetime
  id_col: "unique_key"
  lat_col: "latitude"
  lon_col: "longitude"
  date_col: "created_date"

  hours_before: 23
  hours_after: 0
  
  max_workers: 5
  max_retries: 3
  backoff: 2 

  weather_api:
    query:
      hourly:
        - temperature_2m
        - relative_humidity_2m
        - precipitation
        - windspeed_10m
      daily: null
      timezone: "UTC"

  air_api:
    query:
      hourly:
        - pm10
        - pm2_5
        - carbon_monoxide
        - nitrogen_dioxide
        - ozone
        - sulphur_dioxide
      timezone: "UTC"


us_sanfrancisco:
  country: "us"
  city: "sanfrancisco"

  input_csv: "../../data/datasets/municipal_reports/us/municipal_us_sanfrancisco_311.csv"
  output_csv: "../../data/datasets/weather/us/weather_us_sanfrancisco_open-meteo.csv"

  keep_cols:
    service_request_id: report_id
    lat: latitude
    long: longitude
    requested_datetime: reported_datetime
  id_col: "service_request_id"
  lat_col: "lat"
  lon_col: "long"
  date_col: "requested_datetime"

  hours_before: 23
  hours_after: 0
  
  max_workers: 5
  max_retries: 3
  backoff: 2 

  weather_api:
    query:
      hourly:
        - temperature_2m
        - relative_humidity_2m
        - precipitation
        - windspeed_10m
      daily: null
      timezone: "UTC"

  air_api:
    query:
      hourly:
        - pm10
        - pm2_5
        - carbon_monoxide
        - nitrogen_dioxide
        - ozone
        - sulphur_dioxide
      timezone: "UTC"
