services:
  inference:
    image: vlm:latest
    ports:
      - '8080:8080'
    environment:
      - HF_HOME=/app/cache/huggingface
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - model_weights:/app/cache/huggingface
    gpus: all

volumes:
  model_weights:
