FROM postgres:15

# Install PostGIS, curl, and build tools
RUN apt-get update && apt-get install -y \
    bash git gcc make wget curl unzip \
    postgresql-15-postgis-3 postgresql-15-postgis-3-scripts \
    postgresql-server-dev-15 libgdal-dev libgeos-dev libproj-dev

# Install pgsql-http
RUN git clone https://github.com/pramsey/pgsql-http.git && \
    cd pgsql-http && make && make install

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Default
CMD ["postgres"]
