version: "3.9"

services:
  postgres:
    container_name: database
    build:
      context: ../../
      dockerfile: data_stores/relational_db/Dockerfile.db
    env_file:
      - ../../.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - relational_db_network

  init_db:
    container_name: init_db
    build:
      context: ../../
      dockerfile: data_stores/relational_db/Dockerfile.init_db
    env_file:
      - ../../.env.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/data_stores/relational_db
      - ../../config:/data_stores/relational_db/config
    working_dir: /data_stores/relational_db
    entrypoint: ["/bin/bash", "/data_stores/relational_db/entrypoint_init_db.sh"]
    restart: "no"
    networks:
      - relational_db_network

volumes:
  pgdata:

networks:
  relational_db_network:
    driver: bridge
