version: "3.9"

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - ENV=dev
      - OLLAMA_API_BASE=http://ollama:11434
      - DB_NAME=municipaldb
      - DB_USER=municipaluser
      - DB_PASSWORD=municipalpass
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
      - chroma_data:/app/vector_stores
      - ./models:/app/models
      - .env:/app/.env

  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: municipaldb
      POSTGRES_USER: municipaluser
      POSTGRES_PASSWORD: municipalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "-c", "./entrypoint.sh"]
    tty: true
    restart: always

volumes:
  postgres_data:
  ollama_data:
  chroma_data:
