INSERT INTO issue_subtypes (issue_type_id, name) VALUES
    (1, 'Cockroaches in Food Establishment'),
    (1, 'Mosquitoes'),
    (1, 'Rodents in Common Areas'),
    (1, 'Rodents in Food Establishment'),
    (1, 'Bees & Hornets'),
    (2, 'Dead Animal'),
    (2, 'Injured Animal'),
    (2, 'Bird Issues'),
    (2, 'Cat Issues'),
    (2, 'Dog Issues'),
    (2, 'Other Animal Issues'),
    (3, 'Food Premises'),
    (3, 'Parks & Park Connectors'),
    (3, 'Other Public Areas'),
    (4, 'Fallen Tree/Branch'),
    (4, 'Overgrown Grass'),
    (4, 'Park Lighting Maintenance'),
    (4, 'Park Facilities Maintenance'),
    (4, 'Other Parks and Greenery Issues'),
    (5, 'Choked Drain/Stagnant Water'),
    (5, 'Damaged Drain'),
    (5, 'Flooding'),
    (5, 'Sewer Choke/Overflow'),
    (5, 'Sewage Smell'),
    (6, 'No Water'),
    (6, 'Water Leak'),
    (6, 'Water Pressure'),
    (6, 'Water Quality'),
    (7, 'Construction Noise'),
    (8, 'Cold Storage'),
    (8, 'Giant'),
    (8, 'Mustafa'),
    (8, 'FairPrice'),
    (8, 'ShengSong'),
    (8, 'Ikea'),
    (9, 'Anywheel'),
    (9, 'HelloRide'),
    (9, 'Others'),
    (10, 'Miscellaneous');
