version: "3"

services:
  minio:
    container_name: object_storage
    image: minio/minio
    env_file:
      - ../../.env.dev
    environment:
      MINIO_ROOT_USER: hualaowei_admin
      MINIO_ROOT_PASSWORD: hualaowei_pass
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - object_storage_network

  init_os:
    container_name: init_os
    image: minio/mc
    env_file:
      - ../../.env.dev
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ../..:/app
    entrypoint: ["/bin/sh", "/app/data_stores/object_storage/entrypoint_init_os.sh"]
    restart: "no"
    networks:
      - object_storage_network

volumes:
  minio_data:

networks:
  object_storage_network:
    driver: bridge
