CREATE TABLE IF NOT EXISTS system_config (
  key text PRIMARY KEY,
  value text
);

DROP TABLE IF EXISTS comment_votes CASCADE;
DROP TABLE IF EXISTS post_votes CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS forum_posts CASCADE;
DROP TABLE IF EXISTS issue_status_history CASCADE;
DROP TABLE IF EXISTS issue_media_assets CASCADE;
DROP TABLE IF EXISTS issue_subtype_to_issue_mapping CASCADE;
DROP TABLE IF EXISTS issue_type_to_issue_mapping CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS issue_cat_to_body_mappings CASCADE;
DROP TABLE IF EXISTS jurisdictions CASCADE;
DROP TABLE IF EXISTS subzones CASCADE;
DROP TABLE IF EXISTS planning_areas CASCADE;
DROP TABLE IF EXISTS authorities CASCADE;
DROP TABLE IF EXISTS town_councils CASCADE;
DROP TABLE IF EXISTS agencies CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS subtypes CASCADE;
DROP TABLE IF EXISTS issue_types CASCADE;
DROP TABLE IF EXISTS users CASCADE;