311_us_chicago:
  country: "us"
  city: "chicago"
  domain: "data.cityofchicago.org"
  dataset_id: "v6vf-nfxy"
  limit_per_call: 10000
  app_token: null
  soql:
    select: null
    where: "created_date >= '2025-01-01T00:00:00' AND created_date <= '2025-04-01T23:59:59' AND latitude IS NOT NULL AND longitude IS NOT NULL"
    order: "created_date DESC"
    group: null
  output_csv: "../../data/datasets/municipal_reports/us/municipal_us_chicago_311.csv"


311_us_newyork:
  country: "us"
  city: "newyork"
  domain: "data.cityofnewyork.us"
  dataset_id: "erm2-nwe9"
  limit_per_call: 10000
  app_token: null
  soql:
    select: null
    where: "created_date >= '2025-01-01T00:00:00' AND created_date <= '2025-04-01T23:59:59' AND latitude IS NOT NULL AND longitude IS NOT NULL"
    order: "created_date DESC"
    group: null
  output_csv: "../../data/datasets/municipal_reports/us/municipal_us_newyork_311.csv"


311_us_sanfrancisco:
  country: "us"
  city: "sanfrancisco"
  domain: "data.sfgov.org"
  dataset_id: "vw6y-z8j6"
  limit_per_call: 10000
  app_token: null
  soql:
    select: null
    where: "requested_datetime >= '2025-01-01T00:00:00' AND requested_datetime <= '2025-04-01T23:59:59' AND lat IS NOT NULL AND long IS NOT NULL"
    order: "requested_datetime DESC"
    group: null
  output_csv: "../../data/datasets/municipal_reports/us/municipal_us_sanfrancisco_311.csv"